language: go

go:
- 1.11.x
- 1.12.x


install:
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/...
  - go get -u golang.org/x/lint/golint

script:
  - env GO111MODULE=on make lint
  - env GO111MODULE=on make vet
  - env GO111MODULE=on make test
